### ISSUE TITLE
A connection string is configured but Umbraco could not connect to the database.

### ISSUE THREAD

**Issue by MrMattTaylor** [anthonydotnet/ubase#1]
Hello Anthony,

I've followed the instructions and run the project but I'm seeing the following error so not getting very far.

```
Server Error in '/' Application.
Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.
  at Umbraco.Core.RuntimeState.DetermineRuntimeLevel(IUmbracoDatabaseFactory databaseFactory, ILogger logger) in d:\a\1\s\src\Umbraco.Core\RuntimeState.cs:line 194
  at Umbraco.Core.Runtime.CoreRuntime.DetermineRuntimeLevel(IUmbracoDatabaseFactory databaseFactory, IProfilingLogger profilingLogger) in d:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 259
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in d:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 146 
```

**Comment by MrMattTaylor** [comment]
I've tried setting it up to use IIS and SQL express like all my other projects instead of IIS Express and SQL CE and I get

```
Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Could not check the upgrade state.
```

**Comment by MrMattTaylor** [comment]
I cleared the version number in the web.config and that got the installer going.
With my own connection string in the web.config to my SQL Express DB it just hangs before any dialogues are displayed.
Using the original SQL CE connection string asks you for the account details and then starts but soon errors with 

```
Error during installation

See the log for full details (logs can typically be found in the App_Data\Logs folder).
```
I've attached the log.

[UmbracoTraceLog.LEGOLAS.20200222.json.txt](https://github.com/anthonydotnet/ubase/files/4239450/UmbracoTraceLog.LEGOLAS.20200222.json.txt)

**Comment by anthonydotnet** [comment]
This is an issue with 2 settings in the web.config which I accidentally committed. 

These should be empty:
    <add key="Umbraco.Core.ConfigurationStatus" value="" />
    <add name="umbracoDbDSN" connectionString="" providerName="" />

BTW, I have upgraded Umbraco and fixed these values, so please pull the latest.

**Comment by MrMattTaylor** [comment]
Thanks, it all seems to work nicely now.
I thought the usync import hadn't work properly at first because there's very little content that gets added and the templates are all pretty much blank so you don't see much when the site is run.
I understand that the project is supposed to show how to set up the back-end but it would be a lot easier to understand if there was some working functionality to the site.
I'm still confused about the News document types, they are there but I cannot understand why or how they fit in to the design.

**Comment by anthonydotnet** [comment]
True. I'm trying to walk a fine line, and don't really want it to be a "starterkit" per se. So I guess some functionality can seem oblique. I'm trying to figure out how I can demystify without having to give "examples" that you need to remove. I'll probably settle on some rendering.

I did release 1.3 last night, which might be a little more intuitive.

Ignore news doctypes for now. I'm on the fence about them. Not sure if they should exist in ubase, as they open up a can of worms. eg. tagging, listing page, filtering, hero content. At that point ubase starts to become a starter kit :(

**Comment by MrMattTaylor** [comment]
Great, thanks.

I was a big fan of the Hybrid Framework for Umbraco v7 by Jeroen Breuer.
It had lots of examples of how to do real world things properly which was very helpful but it seems that has stopped with v7.
But yes that was more of a starter kit.
